package com.jlcindia.jaxws.accountclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "AccountServiceDelegate", targetNamespace = "http://account.jaxws.jlcindia.com/")
public interface AccountServiceDelegate {

	/**
	 * 
	 * @param arg0
	 * @return returns double
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getBal", targetNamespace = "http://account.jaxws.jlcindia.com/", className = "com.jlcindia.jaxws.accountclient.GetBal")
	@ResponseWrapper(localName = "getBalResponse", targetNamespace = "http://account.jaxws.jlcindia.com/", className = "com.jlcindia.jaxws.accountclient.GetBalResponse")
	public double getBal(@WebParam(name = "arg0", targetNamespace = "") int arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "deposit", targetNamespace = "http://account.jaxws.jlcindia.com/", className = "com.jlcindia.jaxws.accountclient.Deposit")
	@ResponseWrapper(localName = "depositResponse", targetNamespace = "http://account.jaxws.jlcindia.com/", className = "com.jlcindia.jaxws.accountclient.DepositResponse")
	public void deposit(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") double arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "withdraw", targetNamespace = "http://account.jaxws.jlcindia.com/", className = "com.jlcindia.jaxws.accountclient.Withdraw")
	@ResponseWrapper(localName = "withdrawResponse", targetNamespace = "http://account.jaxws.jlcindia.com/", className = "com.jlcindia.jaxws.accountclient.WithdrawResponse")
	public void withdraw(
			@WebParam(name = "arg0", targetNamespace = "") int arg0,
			@WebParam(name = "arg1", targetNamespace = "") double arg1);

}
